nodeLinker: node-modules
yarnPath: .yarn/releases/yarn-3.2.0.cjs
plugins:
  - path: .yarn/plugins/@yarnpkg/plugin-interactive-tools.cjs
    spec: "@yarnpkg/plugin-interactive-tools"
packageExtensions:
  next-pwa@*:
    peerDependencies:
      "@babel/core": ^7.18.2
      "webpack": "^5.73.0"
logFilters:
  - pattern: "which doesn't satisfy what connected-next-router requests"
    level: discard
