nodeLinker: node-modules
yarnPath: .yarn/releases/yarn-3.2.0.cjs
plugins:
  - path: .yarn/plugins/@yarnpkg/plugin-interactive-tools.cjs
    spec: "@yarnpkg/plugin-interactive-tools"
packageExtensions:
  ts-paths-esm-loader@*:
    peerDependencies:
      "@types/node": ^17.0.31
      typescript: ^4.6.4
  connected-next-router@*:
    peerDependencies:
      react: ^18.1.0
      react-redux: ^8.0.2
